### ISSUE TITLE
variable 'community' referenced before assignment

### ISSUE THREAD

**Issue by synctext** [Tribler/dispersy#102]
As reported by user VVS on [our forum](http://forum.tribler.org/viewtopic.php?f=4&t=3687&p=6974&sid=135550a75397b708f577ec36f5e9c2e2#p6974)

Traceback (most recent call last):
  File "/home/vvs/tribler-6.2.0-rc1/Tribler/dispersy/dispersy.py", line 2703, in store_update_forward
    messages[0].handle_callback(messages)
  File "/home/vvs/tribler-6.2.0-rc1/Tribler/dispersy/dispersy.py", line 2492, in on_introduction_response
    self.wan_address_vote(payload.destination_address, candidate)
  File "/home/vvs/tribler-6.2.0-rc1/Tribler/dispersy/dispersy.py", line 1066, in wan_address_vote
    for candidate in [candidate for candidate in community.candidates.itervalues() if candidate.wan_address == self._wan_address]:
UnboundLocalError: local variable 'community' referenced before assignment

**Comment by NielsZeilemaker** [comment]
Maybe we can create a small unit-test for this bug, seems very trivial to trigger. Then we'll never run into this bug again.

**Comment by boudewijn-tribler** [comment]
Fix: https://github.com/Tribler/dispersy/pull/103

I agree with the unit-test, I'm a bit cramped for time though so will postpone till after my vacation (unless someone else can build one).

**Comment by NielsZeilemaker** [comment]
It's quite strange that this bug wasn't noticed during the new walking_nat tests:
http://jenkins.tribler.org/job/Test_community_walking_NAT/

As there actually symmetric-natted boxes are used, which should trigger this bug. Any clue why we're not seeing any exceptions there?

**Comment by boudewijn-tribler** [comment]
No clue.  There must be a logical explanation though, perhaps Dispersy (#96) or the logger is eating the message?

**Comment by boudewijn-tribler** [comment]
#105 solves the issue with Dispersy/logger hiding exceptions, should prevent exceptions like this from making it through our unit tests.
