### ISSUE TITLE
User specific callback id's should be either unicode or string

### ISSUE THREAD

**Issue by boudewijn-tribler** [Tribler/dispersy#11]
Currently the id_ parameter can be specified as either unicode or string.  This results in warnings, as seen below.

```
/Tribler/dispersy/callback.py:399: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if tup[1] == id_:
```

Solutions:
1. Allow only strings
2. Allow only unicode strings
3. Allow both, but always convert them to either string or unicode string
4. Others?

I prefer to using strings slightly over using unicode.  I am not a fan of the third option, as this results in unnecessary 'under the hood' conversions.

**Comment by NielsZeilemaker** [comment]
replace_register even allows it to be int

**Comment by boudewijn-tribler** [comment]
Yes, this is to allow existing tasks, that have been assigned an id by callback, to be replaced.  

As a rule: integer/long id's are assigned by callback.register while string id's are assigned by the user.

**Comment by NielsZeilemaker** [comment]
For me that's surprising, I would rather go for one type and stick to it. Maybe prepend all "automatic" ids with a prefix. Moreover, I think tasks should stick to unicode as that's used everywhere in Dispersy for identifiers.

In messages, the database etc.

**Comment by boudewijn-tribler** [comment]
I don't mind replacing all auto ids with u"dispersy-#N" or the string equivalent to make it more consistent.

Currently Dispersy isn't very consistent in using either string or unicode for its identifiers, for example, the request cache using strings containing binary cid and mid.  Having these use unicode would require them to be hexified, but perhaps worth doing with issue https://github.com/Tribler/dispersy/issues/7 to make things more consistent.

Anyway, if there are no other opinions/arguments I will change the callback id's into unicode.

**Comment by NielsZeilemaker** [comment]
The RequestCache is using unsigned shorts as ids, or am I mistaken.

2013/4/15 Boudewijn notifications@github.com

**Comment by boudewijn-tribler** [comment]
On the wire an unsigned short is used.  Internally we use strings to match incoming messages to waiting caches, this was previously done with regexp in trigger.py.  See: properties_to_identifier() and message_to_identifier()

We can't use the unsigned short because not all responses can contain this value, unless the responses are all wrapped in a response container message.  We intend to do this in dispersy 2.0, unfortunately we have to use the string matching for now.
