### ISSUE TITLE
Dispersy statistics are global

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#144]
The following dispersy statistics are global, but should be moved to the community statistic object to improve the debugging, i.e. such that we can log how many messages are received per step while doing das experiments.

drop, delay, success, outgoing, created, walk_fail, bootstrap_candidates, walk_attempt, walk_success, walk_bootstrap_attempt, walk_bootstrap_success, walk_reset

I think the received_count, drop_count etc.  should remain global as the community statisctics are removed after unloading a community.

Finally, maybe we can rename success to handled?

**Comment by boudewijn-tribler** [comment]
I agree with all of the above.  This would also be a good opportunity to describe what each statistic contains, as this is not immediately clear for each one.
