### ISSUE TITLE
Candidate.associate not always called

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#147]
Candidate.associate is now only called when receiving a introduction-request or introduction-response.

Although, I agree with comment

``` python
# until we implement a proper 3-way handshake we are going to assume that the creator of
# this message is associated to this candidate
```

I.e., that this is currently easily spoofable. 

Could we change the behaviour to always associate a candidate with a member when receiving any message?
If/when we implement the 3-way handshake message, then this message could overrule the member association by replacing all previously associated members and locking the list.

**Comment by boudewijn-tribler** [comment]
_Any_ message is not possible, i.e. receiving a message that is gossiped around (i.e. votes, permissions, etc) would result in incorrect associations.

Did you mean _any walker_ message?  As in also associate when receiving puncture or puncture-request messages?  

Or did you mean _any non-sync_ message?  This would include all messages that are not spread through bloom filter synchronization.

**Comment by NielsZeilemaker** [comment]
I meant any non-sync message, ie all DirectDistribution messages.

**Comment by boudewijn-tribler** [comment]
Normally DirectDistribution messages are only send between peers that have already contacted each other though the walker, so the association should already be there.

Can you explain the situation where you think this would be useful?

**Comment by NielsZeilemaker** [comment]
In my peercache situation, there I use cached ip addresses to connect to peers without sending them an introduction request. Moreover, I think it makes more sense to just add this line to all DirectDistribution messages than adding it to the walker messages separately.

Reduces code duplication.

**Comment by boudewijn-tribler** [comment]
We will need to create WalkCandidates instead of the Candidate instances, since Candidate instances don't have the associate method, nor are they stored/cached.  But that shouldn't be to much of a problem.

Usually when a WalkCandidate is created either the walk, stumble, or intro method is called.  This sets the timestamps and ensures the WalkCandidate is in the correct category.  A WalkCandidate created from a DirectDistribution message should probably be in the 'none' category (since we do not want it to influence the walk).

But we still need to set at least one of the timestamps (or add another timestamp for this purpose) as otherwise the WalkCandidate will be removed on the next periodic cleanup.

If all of this sounds about right, then I'll make the appropriate changes in the code.

**Comment by NielsZeilemaker** [comment]
I was expecting Dispersy to always attempt to "upgrade" a candidate to a walkcandidate if it is available.
Hence, if a walkcandidate existed the associate method would be called.

I wouldn't go as far as introducing a new timestamp to prevent these walkcandidates from being created, or create walkcandidates for each incomming message.

**Comment by boudewijn-tribler** [comment]
This upgrade from Candidate to WalkCandidate is indeed done in Dispersy.on_incoming_packets, however, from what I understand of your use case, the peers did not yet do an introduction request between them, hence there is no WalkCandidate to upgrade to.  So calling associate only when a WalkCandidate already exists will not solve your problem.

Hence the proposal of creating WalkCandidates not only on introduction-request/response, but also when other messages are received.

**Comment by NielsZeilemaker** [comment]
I my usecase, there is a walkcandidate to upgrade to. As i use create a walkcandidate when connecting to it.

However, this issue isn't as much about my case it is regarding the associate call which is now located in both the on_introduction_request/response methods. I feel it is better to move this call to just after the "upgrade" to a walkcandidate is performed.

Furthermore, I don't see the need of upgrading all candidates to walkcandidates, it doesn't make a lot of sense.
