### ISSUE TITLE
Migrate from dprint to logging

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#15]
Boudewijn and I (I'm sure Niels too :)) think that we should move to the standard python logging system.

Pros:
- Dprint is a custom made logging framework that only a few people understand. 
- We will be able to integrate better with the rest of the python ecosystem (nose comes to mind).
- It will be easier for newcomers to develop and debug dispersy.
- We will trim a bit dispersy's codebase.

The estimate is around a day of work.

Its not a fun task to do but I volunteer to do it.

Johan, do you approve? :)

**Comment by boudewijn-tribler** [comment]
I think the estimate was around a day of work for 2 people.  I volunteer as well.

**Comment by boudewijn-tribler** [comment]
The boring part is done.

All that remains is to create a logger.conf that can be loaded from Tribler/Main/tribler.py or dispersy/tool/main.py (depending on what we are running).

**Comment by boudewijn-tribler** [comment]
Closing for now, we can tweak the existing logger.conf as we see fit, and we can finalize it once we get more familiar with how it works.
