### ISSUE TITLE
CommunityDestination + specificy initial candidates

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#166]
Currently I can assign a number of nodes to push a message to when its created. However, I would like to be able to define to which nodes a message is initially pushed.

Is it possible to extend the CommunityDestination to also allow for a list of candidates to be passed?

**Comment by boudewijn-tribler** [comment]
Yes, this is definitely possible.  Unfortunately I do not have time for this in the near future :(

**Comment by NielsZeilemaker** [comment]
@whirm could you have a go? Please look at the _forward method in dispersy.py it should be a small change.

**Comment by whirm** [comment]
Ok, Ill take a look

**Comment by whirm** [comment]
I will need a bit of help with the unit test for this 
whirm/dispersy@0f3997d
let's do it tomorrow if you are around

**Comment by NielsZeilemaker** [comment]
Ask Boudewijn, I have no clue how to write unittests for Dispersy.

**Comment by whirm** [comment]
@NielsZeilemaker I was talking to @boudewijn-tribler  :)
I will talk to him when he's back on duty.

**Comment by whirm** [comment]
This has been implemented and we have tests for it now.
