### ISSUE TITLE
_encode_member_authentication_signature usage of undefined value 'data'

### ISSUE THREAD

**Issue by Devristo** [Tribler/dispersy#180]
The method _encode_member_authentication_signature of BinaryConversion raises an exception when Sign=False since it attempts to use 'data' which is not available in that scope.

https://github.com/Tribler/dispersy/blob/devel/conversion.py?source=c#L1034

I dont really know what it is supposed to do. Perhaps the data assignment line should be moved up a line?

**Comment by boudewijn-tribler** [comment]
Yea, moving the line up fixes the problem.  Thanks!
