### ISSUE TITLE
We are not power cycling the NAT boxes between experiments

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#2]
We should get a usb/serial controlled power strip to be able to automate power cycling all the NAT boxes before or after a NAT experiment run.

Something similar to this would be good enough:
http://www.amazon.com/PwrUSB-Basic-controlled-Automation-automatically-remotely/dp/B008AZW9P6

**Comment by whirm** [comment]
Power strip ordered

**Comment by whirm** [comment]
I'm getting the ticket again as the power strip is been ordered.

**Comment by whirm** [comment]
The power strip has been installed and we have a script in node300 that allows us to power-cycle all the nat boxes.

We need to decide when to do it.

**Comment by boudewijn-tribler** [comment]
When do the tasks run that use the NAT boxes?  Would x minutes before those tasks start be doable in Jenkins?

**Comment by whirm** [comment]
the thing is that more people is using the cluster, so maybe its better to just do it once during the weekend?

**Comment by boudewijn-tribler** [comment]
I don't know how long it takes before the boxes need a hard reset, if it takes longer than a week, then at the start of the weekend makes sense.  I see no problem as long as everyone using the cluster knows about it.

**Comment by whirm** [comment]
I can't advance on this one until we know what happens with the whole DAS2 thing.

**Comment by whirm** [comment]
Forgot to close this one.
Now the NAT boxes get power cycled before the nightly run.
