### ISSUE TITLE
Batches use callback.priority

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#206]
Currently, the batches are still using the priority of callback. I think this is because Boudewijn wanted to make sure that messages with a higher priority are scheduled sooner. 

However, as deadlines are never equal this doesn't make a lot of sense. Moreover, it doesn't seem to be used.

In the past, priorities have caused problems as they interfere with the scheduling of tasks in the callback. Therefore, I suggest to simply remove them.

**Comment by whirm** [comment]
Are you talking about completely removing priority support in callback?
That would also simplify switching to twisted or similar (twisted doesn't have priorities)

**Comment by NielsZeilemaker** [comment]
Eventually yes, this is the last place in Dispersy which is using priorities. If we remove it here then only Tribler uses the priorities to speed up database queries.

**Comment by NielsZeilemaker** [comment]
Batching does not use priorities in devel anymore
