### ISSUE TITLE
Dispersy needs to immediately exit when an exception occurs

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#24]
So the tests/experiments finish early and we get less cruft to go trough to find the problems.

**Comment by boudewijn-tribler** [comment]
Done. https://github.com/Tribler/dispersy/commit/88a57d13c61be9afadc30f294e301ffc6f466ac0 https://github.com/Tribler/dispersy/commit/49f775dba0741d543ba5c7c7406d9ead726873d4
