### ISSUE TITLE
Timeout-problem in RequestCache

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#3]
During the DAS4 runs I often get this error: 
Looking at the code, this can only be caused by calling the _on_timeout method twice or if the _on_timeout method is still called after the unregistering it.

``` python
"callback.py", line 613, in _loop
    result = call[0](*call[1], **call[2])
"requestcache.py", line 103, in _on_timeout
    cache = self._identifiers[identifier]
KeyError: 33437
```

**Comment by whirm** [comment]
@boudewijn-tribler could you take a look at this one please? its ben sitting there for 3 months now. thx

**Comment by boudewijn-tribler** [comment]
This issue will be difficult to track down, I suggest fixing #7, I suspect that this will either solve this problem or at the very least make this problem much easier to diagnose.
