### ISSUE TITLE
Please create a basic tutorial

### ISSUE THREAD

**Issue by d3vgru** [Tribler/dispersy#32]
A basic tutorial showing how to configure, instantiate, and perform basic operations with dispersy would be very helpful.

**Comment by boudewijn-tribler** [comment]
I have a documentation day this Friday, hopefully I can get around to it then.

**Comment by boudewijn-tribler** [comment]
I have implemented a simple chat room.  The code is linked from the tutorial, and works like a charm.  Even though the UI is a bit lackluster.

https://github.com/boudewijn-tribler/dispersy/blob/documentation/doc/tutorial-part1.org

I would welcome feedback, is this understandable?

Some points from my side:
- github does not correctly parse org files (it uses a very old parser)
- footnotes are rendered inline, which looks horrible
- links inside the document are not parsed correctly, which is also horrible

I'm hoping that the github people upgrade their parser.  Luckily I am not the only one missing these features.

**Comment by boudewijn-tribler** [comment]
https://github.com/Tribler/dispersy/blob/devel/doc/tutorial-part1.org

This will be merged back into the master branch at the next release.
