### ISSUE TITLE
get_introduce_candidate() returns the wrong list of peers

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#343]
Turns out that test_candidates.py was broken so all the tests where passing just OK.

Now I get one failure:
https://github.com/Tribler/dispersy/pull/342

I guess it's due to the introduction of the discovery community?

**Comment by egbertbouman** [comment]
I'm not sure. We did add the discovered category, but I don't know if that should affect dispersy_get_introduce_candidate.

**Comment by whirm** [comment]
This got fixed, somehow it doesn't fail anymore. :/
