### ISSUE TITLE
Dynamic + Linear

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#414]
Something fishy is going on:
http://jenkins.tribler.org//job/GH_Tribler_pull-request-tester_devel/3819/testReport/Tribler.Test.test_remote_search/TestRemoteQuery/test_channelsearch_2/

```
DEBUG   1427121626.94       community:3618  undo message torrent at time 71945
DEBUG   1427121626.94        timeline:440   using PublicResolution for time 72721 (configured at 5)
DEBUG   1427121626.94        timeline:198   FAIL time:72721 user:289 (conflicting resolution policy <LinearResolution> <PublicResolution>)
```

**Comment by NielsZeilemaker** [comment]
```
DEBUG   1427121626.11        timeline:443   using LinearResolution for time 132 (default)
DEBUG   1427121626.11        timeline:198   FAIL time:132 user:289 (conflicting resolution policy <PublicResolution> <LinearResolution>)
DEBUG   1427121626.11        timeline:443   using LinearResolution for time 40498 (default)
DEBUG   1427121626.11        timeline:203   APPLY time:40498 resolution^torrent -> Implementation
DEBUG   1427121626.11        timeline:236   ACCEPT time:40498 user:289 -> permit^torrent (authorized)
```

**Comment by synctext** [comment]
Niels self-assigned himself :-)   thnx! @NielsZeilemaker
The search unit tests have been hurting us for months. Hopefully you identified a key bug to kill.

Today we remixed some Bitcoins and are getting ready to buy some no-questions-asked exit nodes VPS servers for a major release in 2 months or so. Plus hopefully a V6.5 once we close tribler/tribler#1174 coming days.

**Comment by NielsZeilemaker** [comment]
This was quite a nasty bug, actually the dynamicpolicy wasn't implemented correctly. This will hopefully correct this.
