### ISSUE TITLE
Demers exeriment broken

### ISSUE THREAD

**Issue by whirm** [Tribler/dispersy#45]
Should it be fixed, disabled, removed?

**Comment by NielsZeilemaker** [comment]
Should be fixed, no reason for it to be broken.

**Comment by NielsZeilemaker** [comment]
Was due to the allchannel experiment being renamed to _devel.
Running it now to check if it works again.

**Comment by NielsZeilemaker** [comment]
Still broken, das4-peer is attempting to copy dprint.conf to the peers.

http://jenkins.tribler.org/jenkins/job/Experiment_Demers/192/console

**Comment by NielsZeilemaker** [comment]
I'm now getting this error:
No handlers could be found for logger "Tribler.dispersy.dispersy"

I guess that's due to python not finding the logger.conf file. Elric do you know where to put this file? Its now located in the workingdir.

**Comment by whirm** [comment]
Did you try putting it in tool/ yesterday?

**Comment by NielsZeilemaker** [comment]
Yes, we need to update the dispersy reference. The current dispersy branch
does not even configure the logger.conf thingy.

2013/5/2 Elric Milon notifications@github.com

**Comment by NielsZeilemaker** [comment]
The demers experiment runs, but performance is significantly worse than before.
Current performance: http://jenkins.tribler.org/jenkins/job/Experiment_Demers/212/
Before changes to devel: http://jenkins.tribler.org/jenkins/job/Experiment_Demers/189/

I am suspecting the skip to be the cause.

**Comment by whirm** [comment]
Ill disable skip and see if it goes back to normal

**Comment by NielsZeilemaker** [comment]
Whirm, this is still broken. Can you disable the skip in the demerscommunity?
Should be as easy as overwriting the skip variable in the constructor.
