### ISSUE TITLE
Signatures invalid in DoubleMemberAuthentication when forwarding message

### ISSUE THREAD

**Issue by snorberhuis** [Tribler/dispersy#453]
I ran into this bug when I was trying to implement a crawler for MultiChain. 
I wanted to forward a block between two nodes to a third node. I recreate the message with the same payload and into the authentication part I insert the members and signatures.
See:

```
def publish_block(self, candidate, sequence_number):
        requested_block = self.persistence.get_by_sequence_number_public_key(sequence_number, self._public_key)
        if requested_block:
            self._logger.info("Sending block: %s" % sequence_number)
            meta = self.get_meta_message(SIGNATURE)

            requester = self.dispersy.get_member(public_key=requested_block.public_key_requester)
            responder = self.dispersy.get_member(public_key=requested_block.public_key_responder)


            message = meta.impl(authentication=([requester, responder],
                                                [block.signature_requester,
                                                 block.signature_responder]),
                                distribution=(self.claim_global_time(),),
                                destination=(candidate,),
                                payload=requested_block.to_payload())

            self.dispersy.store_update_forward([message], False, False, True)
        else:
            self._logger.info("Received invalid request for block: %s" % sequence_number)
```

When creating the message an exception is throw that the signatures are invalid.
The code is saved in snorberhuis/tribler@b9861567f9c7a400b77c3a4e5b47d539947d86ea

**Comment by snorberhuis** [comment]
Additional I valid all data in the payload to be the same.

**Comment by NielsZeilemaker** [comment]
This isn't a bug. The packet is signed with the private key of both members. You only have the public keys. If you want to forward a message to another peer. Store the packet_id and fetch the raw binary from the dispersy database. 
You cannot reconstruct a packet.

**Comment by snorberhuis** [comment]
You propose a workaround that will probably work. But I think that there is still something wrong, because the code says the signatures are invalid. This should not be case. I am not signing anything, so I don't need the private keys.

**Comment by snorberhuis** [comment]
Or there is something missing in my understanding.

**Comment by NielsZeilemaker** [comment]
Your message has the DoubleMemberAuthentication, which requires two signatures.
None of them are set, hence you're getting an exception stating that the signatures are invalid.

**Comment by NielsZeilemaker** [comment]
Basically, reconstruction is bad. Fetching packet from dispersy database is good.

**Comment by snorberhuis** [comment]
The signatures are inserted in a similar way as responding to a signature_request in the MultiChain community. Why are the signatures not set that way?

```
message = meta.impl(authentication=([requester, responder],
                                                [block.signature_requester,
                                                 block.signature_responder]),
```

Response:

```
message = meta.impl(authentication=(message.authentication.members, message.authentication.signatures),
```

`message.authentication.signatures` returns a simple list with strings.

**Comment by NielsZeilemaker** [comment]
You cannot create signatures without the private key. Hence no signatures are created.
Only the mids are added.

**Comment by snorberhuis** [comment]
The signatures should not have to be created, they are inserted from the database.

**Comment by NielsZeilemaker** [comment]
Basically, reconstruction is bad. Fetching packet from dispersy database is good.
