### ISSUE TITLE
No localhost communication

### ISSUE THREAD

**Issue by qstokkink** [Tribler/dispersy#476]
### Problem

Ever since updating to the latest commit (from 01c6d0131644c3747f953f8eb2bed6f7e3244bd2  to 9cf7d179eb2cb411683cc0095e15994da9b98d28) this morning, my localhost nodes are no longer communicating.
To be precise, the only communication is in the DiscoveryCommunity overlay between 2 nodes (out of many in the overlay).
### Environment/runtime
- I am running [this simple community](https://github.com/qstokkink/VisualDispersy/blob/master/experiments/example_community.py#L29) (which worked on the previous commit) on Ubuntu 15.10 using separate processes.
- [The revised nat unit test suite of the commit](https://github.com/Tribler/dispersy/blob/devel/tests/test_nat_detection.py) passes. 
- This is a portion of the Dispersy info messages (I masked my WAN addresses):

```
estimate someones WAN address is ('X', 7759) (WAN was ('X', 6603), LAN stays ('192.168.0.47', 7759))
estimate someones WAN address is ('X', 7759) (WAN was ('X', 6603), LAN stays ('192.168.0.47', 7759))
estimate someones WAN address is ('Y', 10004) (WAN was ('Y', 54421), LAN stays ('Y', 10004))
estimate someones WAN address is ('X', 7759) (WAN was ('X', 6603), LAN stays ('192.168.0.47', 7759))
estimate someones WAN address is ('Y', 10003) (WAN was ('Y', 54422), LAN stays ('Y', 10003))
estimate someones WAN address is ('Y', 10000) (WAN was ('Y', 54419), LAN stays ('Y', 10000))
estimate someones WAN address is ('Y', 10004) (WAN was ('Y', 54421), LAN stays ('Y', 10004))
estimate someones WAN address is ('Y', 10004) (WAN was ('Y', 54421), LAN stays ('Y', 10004))
estimate someones WAN address is ('X', 7759) (WAN was ('X', 6603), LAN stays ('192.168.0.47', 7759))
estimate someones WAN address is ('Y', 10002) (WAN was ('Y', 54420), LAN stays ('Y', 10002))
estimate someones WAN address is ('Y', 10001) (WAN was ('Y', 54423), LAN stays ('Y', 10001))
estimate someones WAN address is ('Z', 1197) (WAN was ('Z', 7759), LAN stays ('192.168.0.100', 7759))
estimate someones WAN address is ('Z', 1197) (WAN was ('Z', 7759), LAN stays ('192.168.0.100', 7759))
estimate someones WAN address is ('Y', 10002) (WAN was ('Y', 54420), LAN stays ('Y', 10002))
estimate someones WAN address is ('Z', 1197) (WAN was ('Z', 7759), LAN stays ('192.168.0.100', 7759))
estimate someones WAN address is ('Z', 1197) (WAN was ('Z', 7759), LAN stays ('192.168.0.100', 7759))
```

Does anyone know what could be causing this or does anyone have any pointers where I could insert some debugging statements?

**Comment by whirm** [comment]
@pimveldhuisen Please, have a look at this, It seems related to your fallback refactor.

**Comment by synctext** [comment]
interesting. So when running 16-ish Dispersy nodes on a single server it fails. Indeed looks like localhost network 192.168.0.xx detection problem.

**Comment by pimveldhuisen** [comment]
@qstokkink Weird, the commit --shouldn't-- change anything unless you previously had issues with netifaces.
Could you check the value of self._netifaces_failed in dispersy.py?

**Comment by qstokkink** [comment]
@pimveldhuisen _netifaces_failed stays False the entire time.

**Comment by pimveldhuisen** [comment]
@qstokkink Could you try this fix: https://github.com/pimveldhuisen/dispersy/commit/011e8a913dd13b7bda2e5815753edaa8a33cdc70
Either checkout my netifaces_fallback branch (should be up to date with Tribler/devel, except for this commit), or just cherry-pick the commit.

**Comment by qstokkink** [comment]
@pimveldhuisen pimveldhuisen@011e8a913dd13b7bda2e5815753edaa8a33cdc70 works again for me.

**Comment by pimveldhuisen** [comment]
Great! https://github.com/Tribler/dispersy/pull/477 should fix this issue then.

**Comment by pimveldhuisen** [comment]
@whirm this can be closed
