### ISSUE TITLE
Generator only used to get one item?

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/dispersy#494]
The generator here https://github.com/Tribler/dispersy/blob/devel/tests/debugcommunity/node.py#L254
is only used to fetch one message. If it's called twice within the same function, it is done with different `names` parameter.

**Comment by lfdversluis** [comment]
Only case where it is being called twice within the same function: https://github.com/Tribler/dispersy/blob/devel/tests/test_bootstrap.py#L102

**Comment by whirm** [comment]
https://github.com/Tribler/dispersy/blob/devel/tests/debugcommunity/node.py#L288
