### ISSUE TITLE
TaskManager tests are hanging.

### ISSUE THREAD

**Issue by lfdversluis** [Tribler/dispersy#499]
On a fresh clone of Dispersy, running `nosetests tests/test_taskmanager.py` seems to hang indefinitely for me. Apparently they work on BBQ but not for me.

**Comment by lfdversluis** [comment]
Just tested on the debian container, hangs there too. Probably because of the blocking call decorator above the cancel pending task function.

**Comment by whirm** [comment]
Yeah, it's hanging for me too. Really weird as it hasn't changed since 2014...
