### ISSUE TITLE
update_revision_information is broken/obsolete

### ISSUE THREAD

**Issue by boudewijn-tribler** [Tribler/dispersy#5]
When Dispersy was living on SVN, it used keyword expansion (see revision.py) to feed Dispersy (and logging information) with the branch and revision number of the running code.

Git provides similar features through 'smudge' and 'clean' filters (see http://git-scm.com/book/ch7-2.html#Keyword-Expansion)

We need to remove revision.py (since it obviously can not working on git).  And possibly replace it with the filters that Git provides.

**Comment by boudewijn-tribler** [comment]
Right now I prefer to clean up the subversion stuff.  We do not necessarily need to add a similar git feature now.
- https://github.com/Tribler/tribler/pull/87
- https://github.com/Tribler/dispersy/pull/14

**Comment by whirm** [comment]
Just merged it
