### ISSUE TITLE
HardKilledCommunity loaded in LaunchManyCore

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#54]
Tribler LaunchManyCore currently defines the autoload for the HardKilledCommunity. 
Shouldn't this be moved to the dispersy constructor? Or is it Tribler specific?

**Comment by boudewijn-tribler** [comment]
The default Dispersy behavior is to ignore messages from communities that are not defined, having the autoload in LaunchManyCore overrides this behavior, allowing better propagation of killed messages.  

I prefer not to have any autoloads defined by Dispersy.  It can get slightly confusing as Dispersy itself doesn't define any communities, so why should it define any killed communities?  Also, the autoload ordering currently determines the unload community ordering as well.

Ideally, communities should use their own HardKilledCommunity subclass and define (or choose not to) it for auto loading.  So the best solution would be to replace the autoload with community specific autoloads.

**Comment by NielsZeilemaker** [comment]
If it's Tribler specific, then its fine. I was just wondering why it was configured like this.

**Comment by boudewijn-tribler** [comment]
Yea, I'm not liking the way we do the config now.  Since the load=True was included the define_auto_load has become something else.  Perhaps we should rename the method to reflect this change?
