### ISSUE TITLE
Speeding up torrent downloads in Tribler - Peer Video Club

### ISSUE THREAD

**Issue by casbtosint** [Tribler/dispersy#576]
Ускорение загрузки торрентов в Tribler - Peer Video Club
https://peervideo.club/w/sznmzZvyd4dLm817xgwQwT

**Comment by casbtosint** [comment]
Bug or feature?

**Comment by kozlovsky** [comment]
Thank you for reporting the issue; that looks really interesting! We will investigate it!

**Comment by kozlovsky** [comment]
The issue should belong to the [Tribler](https://github.com/Tribler/tribler/) repository, so I'll close it here and reopen it in the appropriate repo
