### ISSUE TITLE
Callback call method hiding Exceptions

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#59]
Whenever an exception occurs in a method which is scheduled using the call method, I get a traceback consisting of the method "calling" the call method.

Could we expose the original traceback?
An example can be found in the Tribler/Main/Utility/GuiDBHandler.py, there I include the traceback into the exception reporting and am printing it to console before raising the exception.

A better solution seems to be to provide the raise statement with the traceback:
http://docs.python.org/2/reference/simple_stmts.html#grammar-token-raise_stmt as suggested here:
http://stackoverflow.com/questions/1603940/how-can-i-modify-a-python-traceback-object-when-raising-an-exception/13898994#13898994

**Comment by boudewijn-tribler** [comment]
Going for the better solution, Pull request is available.
