### ISSUE TITLE
Endpoint not reporting packets which are too large >65k

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#72]
I think we should add an exception if someone is trying to send a packet larger than 65k.
Currently, this will +/- crash the endpoint as it will never be sent.

**Comment by boudewijn-tribler** [comment]
One could argue that checking the max size of the packet is the responsibility of the user.  Similar to checking that the packet is non empty string, which is currently also the responsibility of the user.

Also, you say that this will +/- crash the endpoint, what do you mean by this?  Does it crash, or doesn't it?

**Comment by NielsZeilemaker** [comment]
It will block the endpoint, the packet will not be send due to being too large and hence the endpoint will try again after X seconds.

**Comment by NielsZeilemaker** [comment]
Btw, one could argue that this will help the user debug its community as it's really well hidden that this is causing the endpoint to fail.

**Comment by boudewijn-tribler** [comment]
That is why the user should generally debug its community in debug mode where this check should definitely be included.

**Comment by boudewijn-tribler** [comment]
Niels is right, a bug like this should not go unnoticed if a simple `if` statement can clarify what is going on.  Is #86 sufficient to make endpoint more user friendly?
