### ISSUE TITLE
Encrypt packets send to a candidate

### ISSUE THREAD

**Issue by NielsZeilemaker** [Tribler/dispersy#82]
I want to start encrypting packets which are send to candidates. However, I want to change the encryption-key depending on which candidate.

Therefore, I was thinking of implementing a new endpoint which accepts any other endpoint as a parameter. Next, when sending packets using the send method, this new endpoint would use a callback to figure out if packets send to this candidate should be encrypted or not.
However, as it is now, the endpoint does not know for which community these packets are send. Therefore, it is a bit difficult to encrypt packets for only one community.

Any ideas how I can improve on this idea?

**Comment by boudewijn-tribler** [comment]
I have no good ideas, the only quick (and dirty) hack is to extract the community id from the first few bytes of the packet to determine if it is in a community that should be encrypted or not.  While this could be used for testing/experiments it is not a good approach in the long run.

What is the design?  Is only the endpoint responsible (doing its own crypto handshake) or is it integrated deeper in Dispersy (perhaps negotiating crypto with the walker)?
