### ISSUE TITLE
Investigate if we can replace MemberDestination with CandidateDestination.

### ISSUE THREAD

**Issue by boudewijn-tribler** [Tribler/dispersy#84]
https://github.com/Tribler/dispersy/pull/83#discussion_r5088973.

It would be better to use CandidateDestination instead or MemberDestination.  A simple 'get_candidate_from_member' method should be sufficient, and reduces code complexity by removing the entire MemberDestination policy.

Searching for MemberDestination shows that it is only used for the 'dispersy-signature-request' message.

**Comment by NielsZeilemaker** [comment]
I agree, at least a warning should be generated in the create_signature_request method whenever the _forward method returns false.

**Comment by boudewijn-tribler** [comment]
We need to fix this before the next release, as described in the discussion in #83.

**Comment by boudewijn-tribler** [comment]
https://github.com/Tribler/dispersy/pull/87
