### ISSUE TITLE
Less verbose debug output

### ISSUE THREAD

**Issue by boudewijn-tribler** [Tribler/dispersy#92]
Since we enabled the Dispersy debug output in our nose runs, we have large amounts of output.  Perhaps too much.

The logger provided DEBUG, INFO, WARNING, ERROR, and CRITICAL levels.  Currently most of Dispersy's output is DEBUG while a few select are INFO (i.e. start, stop, IP change, candidate statistics).

There are three options:
1. Keep it as it is (debug output will remain very large)
2. Move all debug to info (no distinction can be made between what is currently info)
3. Put the SQL statements behind a separate `if` flag.
4. Diable the SQL statement output entirely.

**Comment by boudewijn-tribler** [comment]
- Option 2 doesn't allow the distinction between info and debug that we are currently using.
- Option 3 introduces another `if` in the system, and I prefer to avoid doing that (we should only use the logger, with as few exceptions as possible)
- Option 4 seems the lesser evil, and would be my choice.  We can still get database statistics using --runtime-statistics and --explain-query-plan.

**Comment by NielsZeilemaker** [comment]
We could add a special verbose level for just the sql stuff.
http://stackoverflow.com/questions/9042919/python-logging-is-there-something-below-debug

**Comment by boudewijn-tribler** [comment]
That would solve this problem.  But is it the right thing to do here?  It means that we will be using a 'modified' version of the standard logging.  Keeping to the standard has its benefits in readability and cleanness.

As the author of the first post points out: "though the docs say that that should rarely be necessary and may even be undesirable".

**Comment by NielsZeilemaker** [comment]
Don't trust the internets, the docs don't actually say that. They say: "Defining your own levels is possible, but should not be necessary, as the existing levels have been chosen on the basis of practical experience."

However, I do agree with you that is seems to be a bit of a hack. Alternatively we could simply use the NOTSET level.

``` python
logger.log(logging.NOTSET, 'msg')
```

**Comment by boudewijn-tribler** [comment]
Yes, using NOTSET would be a good alternative.
